spring:
  profiles:
    active: dev
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888" # Connects to vault
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh # Required for dynamic refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  # Base64-encoded 256-bit key.
  # In a real enterprise app, you would never hardcode this
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day in milliseconds